name: Validate repos.json

on:
  push:
    branches:
    - gh-pages
    paths:
    - 'resources/repos.json'
  pull_request:
    branches:
    - gh-pages
    paths:
    - 'resources/repos.json'

jobs:
  validate:
  
    name: Validate JSON
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Validate JSON
      uses: docker://orrosenblatt/validate-json-action:latest@sha256:02370758b8b199e0477da11ecfdd498c75c561685056b5c31b925a4ab95df7f4
      env:
        INPUT_SCHEMA: resources/schema.json
        INPUT_JSONS: resources/repos.json
